"""Suggested-policy generator: observed calls -> draft schema + policy code.

Run your agent under a dry-run gate (or warn-mode shield), then call
suggest_policies(gate) to get a reviewable Python draft. The draft reflects
only what was observed; a human must widen, tighten, and approve every line.
"""

from __future__ import annotations

from typing import Any

from toolwall.intake import ToolCall


def _type_name(value: Any) -> str:
    return type(value).__name__


def _collect(calls: "list[ToolCall]") -> dict[str, dict[str, Any]]:
    tools: dict[str, dict[str, Any]] = {}
    for call in calls:
        info = tools.setdefault(call.name, {"count": 0, "args": {}})
        info["count"] += 1
        for key, value in call.args.items():
            arg = info["args"].setdefault(
                key, {"types": set(), "seen_in": 0, "numeric": [], "strings": set()}
            )
            arg["seen_in"] += 1
            arg["types"].add(_type_name(value))
            if isinstance(value, bool):
                pass
            elif isinstance(value, (int, float)):
                arg["numeric"].append(value)
            elif isinstance(value, str) and len(arg["strings"]) <= 8:
                arg["strings"].add(value)
    return tools


def suggest_policies(source: Any) -> str:
    """Generate draft register() calls from a Gate (uses .history) or ToolCall list."""
    if hasattr(source, "history"):
        calls = [r.call for r in source.history if r.call is not None]
    else:
        calls = list(source)
    if not calls:
        return "# No tool calls observed yet. Run the agent under a dry-run gate first.\n"

    tools = _collect(calls)
    lines = [
        "# Draft policies generated by toolwall.suggest_policies",
        f"# Observed: {len(calls)} call(s) across {len(tools)} tool(s).",
        "# REVIEW EVERY LINE. Ranges and enums reflect only what was observed;",
        "# widen deliberately, and decide which tools need require_approval.",
        "",
        "from toolwall import Policy, ToolSchema, in_range, not_empty, one_of",
        "",
    ]

    for name, info in sorted(tools.items()):
        args = info["args"]
        required = sorted(k for k, a in args.items() if a["seen_in"] == info["count"])
        types = {
            k: sorted(a["types"])[0]
            for k, a in sorted(args.items())
            if len(a["types"]) == 1
        }
        constraints: list[str] = []
        for key, arg in sorted(args.items()):
            if arg["numeric"]:
                lo, hi = min(arg["numeric"]), max(arg["numeric"])
                constraints.append(
                    f'        "{key}": in_range({lo}, {hi}),  # observed {lo}..{hi}; widen if needed'
                )
            elif arg["strings"] and len(arg["strings"]) <= 3:
                values = ", ".join(repr(v) for v in sorted(arg["strings"]))
                constraints.append(
                    f'        "{key}": one_of({values}),  # only these values observed'
                )

        types_src = ", ".join(f'"{k}": {t}' for k, t in types.items())
        lines.append(f"gate.register(")
        lines.append(f'    "{name}",')
        lines.append(f"    {name},  # TODO: point at your real callable")
        lines.append(
            f"    schema=ToolSchema(required={required!r}, types={{{types_src}}}),"
        )
        if constraints:
            lines.append("    policy=Policy(constraints={")
            lines.extend(constraints)
            lines.append("    }),  # TODO: add require_approval=True if destructive")
        else:
            lines.append("    # TODO: no value constraints inferred; add Policy() by hand")
        lines.append(")")
        lines.append("")

    return "\n".join(lines)
